l1_logreg: src_c/classify.c File Reference
src_c/classify.c File Reference
Classify test data.
#include "pkgdef.h"
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "def.h"
#include "l1_logreg.h"
#include "util.h"
Defines
#define BUFFER_SIZE 1024
Functions
int main (int argc, char *argv[])
Classify data with given model.
Detailed Description
Classify test data.
Function Documentation
int main (int argc, char * argv[])
Classify data with given model.
Parameters:
argc number of argument.
argv array of input arguments.
< feature matrix
< class vector
< result [+1,-1]
References dmat_build_idx(), dmat_free(), dmatrix::idx, dmatrix::jdx, l1_logreg_classify(), dmatrix::m, dmatrix::n, dmatrix::nz, dmatrix::rdx, read_mm_new_matrix(), read_mm_new_vector(), and dmatrix::val.